# Generated by Django 6.0.1 on 2026-02-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysis',
            options={'verbose_name': 'AI Analysis', 'verbose_name_plural': 'AI Analyses'},
        ),
    ]
