# Generated by Django 6.0.1 on 2026-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_alter_aianalysis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='coping_suggestion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
