# Generated by Django 6.0.1 on 2026-02-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_aianalysis_coping_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='primary_emotion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='risk_level',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
